# Generated by Django 3.1.1 on 2020-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('typeClub', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type Club')),
                ('clubMembers', models.ManyToManyField(blank=True, to='crudapp.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='membre',
            field=models.ManyToManyField(blank=True, to='crudapp.Club'),
        ),
    ]
