# Generated by Django 3.1.1 on 2020-09-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_auto_20200924_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='clubMembers',
        ),
    ]
