# Generated by Django 3.1.1 on 2020-09-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_remove_club_clubmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('typeActivity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type Activity')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='clubActivity',
            field=models.ManyToManyField(blank=True, to='crudapp.Activity'),
        ),
    ]
