# Generated by Django 3.1.1 on 2020-10-04 15:18

from django.db import migrations, models
#from .models import path_and_rename
from django.utils.deconstruct import deconstructible

@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)

path_and_rename = PathAndRename("/static")

class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_contact_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='display_pictur',
            field= models.ImageField(
                               upload_to=path_and_rename,
                               null=True, blank=True,
                               default="media/static/telechargement.png",
                               height_field="image_height",
                               width_field="image_width")
            
        ),
    ]
"""models.FileField(default='static\telechargement.png', upload_to='media\'),
            preserve_default=False,"""
"""
        migrations.RemoveField(
            model_name='contact',
            name='display_picture',
        ),"""