# Generated by Django 3.1.1 on 2020-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20201004_1618'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='contact',
            name='display_pictur',
            field=models.ImageField(blank=True, default='media/static/telechargement.jpg', upload_to='/static/'),
        ),
    ]
"""migrations.RemoveField(
            model_name='contact',
            name='display_picture',
        ),"""