# Generated by Django 3.1.1 on 2020-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_auto_20201006_1921'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='contact',
            name='display_pictur',
            field=models.ImageField(blank=True, default='media/static/telechargement.jpg', upload_to='media/static'),
        ),
    ]
