# Generated by Django 3.1.1 on 2020-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_auto_20201006_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='display_picture',
        ),
        migrations.AlterField(
            model_name='contact',
            name='display_pictur',
            field=models.ImageField(blank=True, default='crudapp/templates/media/static/telechargement.jpg', upload_to='crudapp/templates/media/'),
        ),
    ]
